### ISSUE TITLE
kwin-plugins not compatible kde-5.23.0

### ISSUE THREAD

**Issue by HougeLangley** [cutefishos/kwin-plugins#7]
I build this one in Gentoo Linux with `~amd` branch which means Test or development branch. got this errors.

![photo_2021-10-15_10-24-02](https://user-images.githubusercontent.com/1161594/137422485-0ee8ab4b-b5f6-4267-8406-06f559664c43.jpg)

![photo_2021-10-15_10-24-18](https://user-images.githubusercontent.com/1161594/137422505-73574095-96ae-4e67-90b6-20ffe3d2dd5d.jpg)

if I use this command check kwin-5.22.x and kwin-5.23 diff.

This is kwin-5.22.x's
```
grep -A 7 -B 2 MapTexture /usr/include/kwinglutils.h

enum class ShaderTrait {
    MapTexture       = (1 << 0),
    UniformColor     = (1 << 1),
    Modulate         = (1 << 2),
    AdjustSaturation = (1 << 3),
    ClampTexture     = (1 << 4),
};

Q_DECLARE_FLAGS(ShaderTraits, ShaderTrait)
```
This one is kwin-5.23.x's

![photo_2021-10-15_10-25-25](https://user-images.githubusercontent.com/1161594/137422703-c0430fe5-a1ac-4c35-99e4-5f88be04b766.jpg)

**Comment by AmberisMyShiba** [comment]
I tried to modify the source file and add  the conent `ClampTexture     = (1 << 4),` in /usr/include/kwinglutils.h,and then builded again.It shows me another error with following message

> error: ‘class KWin::WindowPaintData’ has no member named ‘quads’
I think kwin-plugins still has more workloads to process for compatibility
